# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create(:name=>'Action')
Category.create(:name=>'Adventure')
Category.create(:name=>'Animation')
Category.create(:name=>'Biography')
Category.create(:name=>'Comedy')
Category.create(:name=>'Crime')
Category.create(:name=>'Documentary')
Category.create(:name=>'Drama')
Category.create(:name=>'Family')
Category.create(:name=>'Fantasy')
Category.create(:name=>'Film-Noir')
Category.create(:name=>'Game-Show')
Category.create(:name=>'History')
Category.create(:name=>'Horror')
Category.create(:name=>'Music')
Category.create(:name=>'Musical')
Category.create(:name=>'Mystery')
Category.create(:name=>'News')
Category.create(:name=>'Reality-TV')
Category.create(:name=>'Romance')
Category.create(:name=>'Sci-Fi')
Category.create(:name=>'Sport')
Category.create(:name=>'Talk-Show')
Category.create(:name=>'Thriller')
Category.create(:name=>'War')
Category.create(:name=>'Western')

Category.create(:name=>'Uncategorized')
